apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dogecoind-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi