apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-docker-entrypoint-initdb-d
  namespace: {{ .Values.namespace }}
data:
  create_db.sql: |
    CREATE DATABASE IF NOT EXISTS `shkeeper`;
    CREATE DATABASE IF NOT EXISTS `tron-shkeeper`;
