{{- if or .Values.bnb.enabled .Values.bnb_usdt.enabled .Values.bnb_usdc.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: bnb-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: bnb-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}
