{{- if .Values.xrp.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: xrp-shkeeper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: xrp-shkeeper
  ports:
  - name: app-tcp
    port: 6000
    protocol: TCP
{{ end }}
