#
# General
#

namespace: shkeeper
external_ip: 0.0.0.0

dev:
  imagePullSecrets:

storageClassName:

#
# Shkeeper
#

shkeeper:
  image: vsyshost/shkeeper:2.2.4
  port: 5000

#
# Tron
#

tron_fullnode:
  enabled: false
  #url: http://java-tron:8090
  #solidity_url: http://java-tron:8091
  url: http://fullnode.tron.shkeeper.io
  mainnet: true
  #JAVA_TOOL_OPTIONS: ""
  #nodeSelector: {}
  #tolerations: []

tron_shkeeper:
  image: vsyshost/tron-shkeeper:1.1.1
  host: 'tron-shkeeper'
  port: 6000

trx:
  enabled: true
usdt:
  enabled: true
usdc:
  enabled: false
