{{- if .Values.doge.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogecoind-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: dogecoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogecoind
  template:
    metadata:
      labels:
        app: dogecoind
    spec:
      containers:

      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/templates/default.conf.template
          subPath: default.conf.template
        - mountPath: /backup
          name: backup
        env:
        - name: SHKEEPER_BACKEND_KEY
          valueFrom:
            secretKeyRef:
              name: shkeeper-btc-key
              key: password


      - name: dogecoind
        image: vsyshost/dogecoind
        {{- if not .Values.doge.mainnet }}
        command:
        - /shkeeper/dogecoind
        - -testnet
        - -prune=2200
        - -rpcport=22555
        - -rpcpassword=$DOGE_PASSWORD
        - -rpcuser=$DOGE_USERNAME
        - -rpcbind=0.0.0.0
        - -rpcallowip=0.0.0.0/0
        - -wallet=shkeeper
        - -walletnotify=/shkeeper/walletnotify.sh %s
        {{- end }}
        env:
          - name: DOGE_USERNAME
            valueFrom:
              secretKeyRef:
                name: dogecoin-rpc
                key: username
                optional: false
          - name: DOGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dogecoin-rpc
                key: password
                optional: false
          - name: SHKEEPER_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
                optional: false
        volumeMounts:
        - name: dogecoind-storage
          mountPath: /root/.dogecoin
        - name: backup
          mountPath: /backup
      volumes:
      - name: dogecoind-storage
        persistentVolumeClaim:
          claimName: dogecoind-claim
      - name: backup
        emptyDir:
          medium: Memory
      - name: nginx-config
        configMap:
          name: nginx-config
{{- end }}
