{{- if .Values.monero.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: monero-wallet-rpc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: monero-wallet-rpc
  ports:
  - name: api
    port: 2222
    targetPort: api
{{ end }}